# this will create token for serviceacoount jenkins that has role to access necessary resource of kibernates
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: mysecretname
  namespace: webapps
  annotations:
    kubernetes.io/service-account.name: jenkins #jenkins
